### PR TITLE
Fix composer version

### PR DESCRIPTION
**Pull request by norgeindian**
According to `magento-phpstan/action.yml`, the default version should be 2.

### CODE REVIEW

**Review by sprankhub — APPROVED** [review]
I think this makes sense and also matches what we e.g. do in integration tests:

https://github.com/extdn/github-actions-m2/blob/d213f57b07128c575002f32bfd724f808ae1ec22/magento-integration-tests/entrypoint.sh#L18

However, I would love to have an eye from someone else as well here.

**Comment by jissereitsma** [comment]
I'm in favor of quick fixing here. Most developers should be using composer 2 anyway, because we live in modern times. If people still want to fall back to composer 1, this can be overridden anyway.

**Comment by jissereitsma** [comment]
First issue already, PHP 7.3 and older Magento versions will not work with composer 2: https://github.com/extdn/github-actions-m2/commit/6eca205972c00543408e36514b18bcdd7ce1b2c7

**Comment by norgeindian** [comment]
@jissereitsma , something is still wrong:

image

Do you see any reason for this strange behaviour?

**Comment by jissereitsma** [comment]
@norgeindian For which PHP version is this? The current `entrypoint.sh` shows a message "Setup extension source folder within Magento root" (which is shown in your screenshot too), but right before that it should give a message "Using composer 2" (which in your case is not showing). So it would be my guess, that the wrong version is used or that the right Docker version is never built.

Currently you are using `extdn/magento-phpstan-action:latest` but this was not changed in 3 years, since the [images](https://hub.docker.com/r/extdn/magento-phpstan-action/tags) were refactored for different PHP versions. The image version you should be looking for is `extdn/magento-phpstan-action:7.4-latest` or similar.

**Comment by norgeindian** [comment]
@jissereitsma , thanks for the fast reply.
This is my `phpstan.yml`:

```
name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extdn/github-actions-m2/magento-phpstan@master
        with:
          composer_name: customgento/module-mass-update-tier-prices-m2
          composer_version: 2
``` 
I more or less copied it from the readme. So am I doing something wrong here?

**Comment by jissereitsma** [comment]
yes, if you change `uses: extdn/github-actions-m2/magento-phpstan@master` to `uses: extdn/github-actions-m2/magento-phpstan/8.1@master` like here: https://github.com/extdn/github-actions-m2/blob/master/examples/extdn-phpstan.yml

**Comment by norgeindian** [comment]
@jissereitsma , thanks a lot. That seems to work now. Would you agree, that we should adapt that in the README, so it's more obvious to everyone how it works? Then I will be happy to provide a PR.

**Comment by jissereitsma** [comment]
Good point. I've update the README already :)

**Pull request merged**
