### PR TITLE
static code analysis with the PHPCompatibility Coding Standard

### PR DESCRIPTION
**Pull request by DomPixie**
Apologies I'm on a windows machine at the moment so can't fully test this e.g can't even clone repo due to file naming convention. And can only do so much using WSL.

So basically I've taken a wild stab in the dark on how I think this should work. Could need further work. Also what that means is that I can't do a great deal of editing if changes are required to the PR.

Personally for me I think it would be really handy to have a static code analysis with the specifically the PHPCompatibility coding standard but allowing adjustment of test version.

### CODE REVIEW

**Comment by jissereitsma** [comment]
Hi @DomPixie awesome work so far. I definitely think people will benefit from this. I actually had this myself on the todo list, so ... checked (thanks to your work).

I don't know about the whole `problem-matcher.json` thingy, but trust that you put thought into it. And because the PR is only adding a new workflow action instead of changing existing ones, I think it is pretty safe to just accept it, implement it in some repos and see how it goes.

**Comment by DominicWatts** [comment]
Hi

Any chance the docker images can be pushed up? I can then give it a try.

**Comment by jissereitsma** [comment]
The Docker images are actually built in runtime through the GitHub Actions of this very same repo: So a Docker-file  https://github.com/extdn/github-actions-m2/blob/master/php-compatibility/Dockerfile:7.4 is picked up by https://github.com/extdn/github-actions-m2/blob/master/.github/workflows/docker.yml - but I see this only does so for specific folders. Let me see if I can quickly fix this myself.

**Comment by jissereitsma** [comment]
New Docker images are now built based on v1.0.12: https://github.com/extdn/github-actions-m2/actions Cross fingers that this works.

**Comment by jissereitsma** [comment]
And apparently it fails.

**Pull request merged**
